version: '3.2'
services:
  postgres:
    hostname: postgres
    image: postgres:13
    ports:
      - 0.0.0.0:5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    hostname: redis
    image: redis
    ports:
      - 0.0.0.0:6379:6379
  server:
    hostname: server
    container_name: server
    image: jarr-server:latest
    volumes:
      - "/home/circleci/project/Makefile:/jarr/Makefile"
      - "/home/circleci/project/tests:/jarr/tests"
      - "/home/circleci/project/example_conf:/etc/jarr"
      - "/home/circleci/coverage_results:/jarr/coverage_results:rw"
