version: '3'
services:
  jarr-server:
    build:
      context: ../.
      dockerfile: ./Dockerfiles/server
    ports:
      - "127.0.0.1:8500:8000"
    # You'll a folder with at least jarr.json, logging.ini and gunicorn.py
    volumes:
      - ../example_conf/:/etc/jarr:ro
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      jarr:
  jarr-front:
    build:
      context: ../.
      dockerfile: ./Dockerfiles/front
      args:
        PUBLIC_URL: http://localhost:8501/
        REACT_APP_API_URL: http://localhost:8500/
    ports:
      - "127.0.0.1:8501:80"
    depends_on:
      - jarr-server
    networks:
      - jarr
  jarr-worker:
    build:
      context: ../.
      dockerfile: ./Dockerfiles/server
    # You'll a folder with at least jarr.json, logging.ini and gunicorn.py
    volumes:
      - ../example_conf/:/etc/jarr:ro
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - jarr
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq
    networks:
      - jarr
  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      - jarr
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - jarr
    # remove that on real prod env and set proper db password
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    # Directory in which your db will save its data, change it to some absolute path
    # volumes:
    #  - ../.jarr-data:/var/lib/postgresql/data

networks:
  jarr:
