"""empty message

Revision ID: cad754e6b832
Revises: ce7bfcdd21fc
Create Date: 2020-04-17 21:46:45.962122

"""
import logging
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'cad754e6b832'
down_revision = 'ce7bfcdd21fc'
branch_labels = None
depends_on = None
logger = logging.getLogger('alembic.' + revision)


def upgrade():
    logger.info("creating type for articles")
    article_type = postgresql.ENUM('image', 'video', 'embedded',
                                   name='articletype')
    article_type.create(op.get_bind())
    op.add_column('article', sa.Column('article_type', article_type,
                                       nullable=True, default=None))
    logger.info("complex content for cluster")
    op.add_column('cluster', sa.Column('content',
                                       sa.PickleType(), nullable=True))

    logger.info("altering article indexes")
    op.create_index('ix_cluster_uid_martid', 'cluster',
                    ['user_id', sa.text('main_article_id NULLS FIRST')],
                    unique=False)
    op.drop_index('ix_cluster_martid', table_name='cluster')
    op.create_index('ix_cluster_martid', 'cluster',
                    [sa.text('main_article_id NULLS LAST')], unique=False)
    op.drop_index('cluster_main_aid', table_name='cluster')
    op.drop_index('cluster_uid_maid', table_name='cluster')

    logger.info("creating types for feed")
    feedtype = postgresql.ENUM('classic', 'json', 'tumblr', 'instagram',
                               'soundcloud', 'reddit', 'fetch', 'koreus',
                               'twitter', name='feedtype')
    feedtype.create(op.get_bind())
    op.add_column('feed', sa.Column('feed_type', feedtype,
                                    nullable=True, default='classic'))
    logger.info("migrating to new feed status mech")
    feedstatus = postgresql.ENUM('active', 'paused', 'to_delete', 'deleting',
                                 name='feedstatus')
    feedstatus.create(op.get_bind())
    op.add_column('feed', sa.Column('status', feedstatus,
                                    default='active', nullable=True))

    logger.info("migration feed types and status to new values")
    op.execute("""UPDATE feed SET feed_type='reddit'
                  WHERE integration_reddit=true""");
    op.execute("""UPDATE feed SET feed_type='tumblr',
                  last_error='', error_count=0
                  WHERE link LIKE '%.tumblr.com%'""");
    op.execute("UPDATE feed SET feed_type='classic' WHERE feed_type IS NULL;")
    op.execute("UPDATE feed SET status='active' WHERE enabled=true");
    op.execute("UPDATE feed SET status='paused' WHERE enabled=false");
    op.alter_column('feed', 'feed_type',
                    existing_type=feedtype, nullable=False)
    op.alter_column('feed', 'status', existing_type=feedstatus, nullable=False)

    logger.info("droping feed obsolete column")
    op.drop_column('feed', 'integration_reddit')
    op.drop_column('feed', 'readability_auto_parse')
    op.drop_column('feed', 'enabled')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('feed', sa.Column('readability_auto_parse', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('feed', sa.Column('integration_reddit', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('feed', 'status')
    op.drop_column('feed', 'feed_type')
    op.create_index('cluster_uid_maid', 'cluster', ['user_id', 'main_article_id'], unique=False)
    op.create_index('cluster_main_aid', 'cluster', ['main_article_id'], unique=False)
    op.drop_index('ix_cluster_martid', table_name='cluster')
    op.create_index('ix_cluster_martid', 'cluster', ['user_id', 'main_article_id'], unique=False)
    op.drop_index('ix_cluster_uid_martid', table_name='cluster')
    op.drop_column('article', 'article_type')
    # ### end Alembic commands ###
