"""Add more article type

revision id: 511346f4372e
revises: f4543055e780
create date: 2021-04-03 19:57:53.312419

"""

# revision identifiers, used by alembic.
revision = '511346f4372e'
down_revision = 'f4543055e780'
branch_labels = none
depends_on = none

from alembic import op
import sqlalchemy as sa
from jarr.lib.enums import ArticleType


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
