"""empty message

Revision ID: a987c6ce888d
Revises: 00c5cc87408d
Create Date: 2018-08-01 18:34:00.415937

"""

# revision identifiers, used by Alembic.
revision = 'a987c6ce888d'
down_revision = '8079a1cb5874'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('article_uid', table_name='article')
    op.drop_index('article_uid_cid_cluid', table_name='article')
    op.drop_index('article_uid_cluid', table_name='article')
    op.drop_index('article_uid_fid_cluid', table_name='article')
    op.drop_index('article_uid_fid_eid', table_name='article')
    op.drop_column('category', 'cluster_on_title')
    op.add_column('cluster', sa.Column('content', sa.String(), nullable=True))
    op.drop_index('cluster_liked_uid_date', table_name='cluster')
    op.drop_index('cluster_read_uid', table_name='cluster')
    op.drop_index('cluster_read_uid_cluid', table_name='cluster')
    op.drop_index('cluster_read_uid_date', table_name='cluster')
    op.add_column('feed', sa.Column('cluster_enabled', sa.Boolean(), nullable=True))
    op.add_column('feed', sa.Column('cluster_tfidf_enabled', sa.Boolean(), nullable=True))
    op.add_column('feed', sa.Column('cluster_same_category', sa.Boolean(), nullable=True))
    op.add_column('feed', sa.Column('cluster_same_feed', sa.Boolean(), nullable=True))
    op.add_column('feed', sa.Column('cluster_wake_up', sa.Boolean(), nullable=True))
    op.add_column('feed', sa.Column('cluster_config', sa.PickleType(), nullable=True))
    op.add_column('category', sa.Column('cluster_enabled', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('cluster_tfidf_enabled', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('cluster_same_category', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('cluster_same_feed', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('cluster_config', sa.PickleType(), nullable=True))
    op.add_column('user', sa.Column('cluster_enabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('cluster_tfidf_enabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('cluster_same_category', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('cluster_same_feed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('cluster_config', sa.PickleType(), nullable=True))
    op.drop_index('idx_feed_uid_cid', table_name='feed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_feed_uid_cid', 'feed', ['user_id', 'category_id'], unique=False)
    op.drop_column('feed', 'cluster_config')
    op.drop_column('feed', 'cluster_same_feed')
    op.drop_column('feed', 'cluster_same_category')
    op.drop_column('feed', 'cluster_tfidf_enabled')
    op.drop_column('feed', 'cluster_enabled')
    op.drop_column('feed', 'cluster_wake_up')
    op.drop_column('category', 'cluster_config')
    op.drop_column('category', 'cluster_same_feed')
    op.drop_column('category', 'cluster_same_category')
    op.drop_column('category', 'cluster_tfidf_enabled')
    op.drop_column('category', 'cluster_enabled')
    op.drop_column('user', 'cluster_config')
    op.drop_column('user', 'cluster_same_feed')
    op.drop_column('user', 'cluster_same_category')
    op.drop_column('user', 'cluster_tfidf_enabled')
    op.drop_column('user', 'cluster_enabled')
    op.create_index('cluster_read_uid_date', 'cluster', ['read', 'user_id', 'main_date'], unique=False)
    op.create_index('cluster_read_uid_cluid', 'cluster', ['read', 'user_id', 'id'], unique=False)
    op.create_index('cluster_read_uid', 'cluster', ['read', 'user_id', 'id'], unique=False)
    op.create_index('cluster_liked_uid_date', 'cluster', ['liked', 'user_id', 'main_date'], unique=False)
    op.drop_column('cluster', 'content')
    op.add_column('category', sa.Column('cluster_on_title', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('article_uid_fid_eid', 'article', ['user_id', 'feed_id', 'entry_id'], unique=False)
    op.create_index('article_uid_fid_cluid', 'article', ['user_id', 'feed_id', 'cluster_id'], unique=False)
    op.create_index('article_uid_cluid', 'article', ['user_id', 'cluster_id'], unique=False)
    op.create_index('article_uid_cid_cluid', 'article', ['user_id', 'category_id', 'cluster_id'], unique=False)
    op.create_index('article_uid', 'article', ['user_id'], unique=False)
    # ### end Alembic commands ###
